name: Deploy to Azure 

on:
  pull_request:
    branches: [main]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v3
      with:
        app-name: 'my-web-app-2025'
        slot-name: 'staging'
        package: '.'
    - run: sed -i 's/HTTPSample\.domain">[^<]*/HTTPSample.domain">my-web-app-2025-staging-cyhzghehbeeyhsc8.uksouth-01.azurewebsites.net/g' test1.jmx
    - uses: azure/load-testing@v1
      with:
        loadTestConfigFile: 'test1.yml'
        loadTestResource: 'loadTestResults'
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: loadTestResults
        path: loadTest/results.zip
