name: wk1

on:
   workflow_dispatch:
   

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v3
      with:
        app-name: 'my-web-app-2025'
        slot-name: 'staging'
        package: '.'
  
