name: wk2

on:
  workflow_run:
    workflows: deploy 
    types:
      - completed

jobs:
  swap-slots:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Swap Slots
        run: az webapp deployment slot swap --resource-group my-web-app-2025_group --name my-web-app-2025 --slot staging
